"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
type Item = { id: string; title: string; type: string; category: string; summary: string; content: string; published: boolean; sort: number };
const blank: Omit<Item,"id"> = { title: "", type: "笔记", category: "思考", summary: "", content: "", published: false, sort: 0 };
async function api(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "请求失败"); return body; }
export default function Studio() {
  const [items,setItems]=useState<Item[]>([]), [editor,setEditor]=useState(false), [query,setQuery]=useState(""), [error,setError]=useState(""), [loading,setLoading]=useState(true), [editing,setEditing]=useState<Item|null>(null), [showLogin,setShowLogin]=useState(false);
  const load=async()=>{setLoading(true);setError("");try{const data=await api("/api/content");setItems(data.items);setEditor(data.editor)}catch(e){setError(e instanceof Error?e.message:"加载失败")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>items.filter(i=>`${i.title} ${i.summary} ${i.content} ${i.category}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{await api("/api/auth",{method:"POST",body:JSON.stringify({password:form.get("password")})});await api("/api/setup",{method:"POST",body:"{}"});setShowLogin(false);await load()}catch(e){setError(e instanceof Error?e.message:"登录失败")}}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const value={title:String(f.get("title")),type:String(f.get("type")),category:String(f.get("category")),summary:String(f.get("summary")),content:String(f.get("content")),published:f.get("published")==="on",sort:Number(f.get("sort"))};try{await api(editing?.id?`/api/content/${editing.id}`:"/api/content",{method:editing?.id?"PATCH":"POST",body:JSON.stringify(value)});setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:"保存失败")}}
  return <main><header><a className="brand" href="#">QIAO<span>·</span>GARDEN</a><nav><a href="#projects">项目</a><a href="#notes">笔记</a><button onClick={()=>editor?setEditing({id:"",...blank}):setShowLogin(true)}>{editor?"＋ 新建":"编辑"}</button></nav></header>
    <section className="hero"><p className="eyebrow">PERSONAL DIGITAL GARDEN</p><h1>把好奇心，<br/>变成可分享的作品。</h1><p>这里收集我的项目、思考与学习笔记。内容由 Notion 驱动，也可以直接在网站中编辑。</p><input aria-label="搜索" placeholder="搜索项目、笔记或标签…" value={query} onChange={e=>setQuery(e.target.value)}/></section>
    {error&&<p className="error">{error}</p>}{loading?<p className="status">正在从 Notion 读取…</p>:<><Section id="projects" title="项目" items={visible.filter(i=>i.type==="项目")} editor={editor} edit={setEditing}/><Section id="notes" title="笔记" items={visible.filter(i=>i.type!=="项目")} editor={editor} edit={setEditing}/></>}
    <footer>© {new Date().getFullYear()} Qiao · Powered by Notion</footer>
    {showLogin&&<Dialog title="进入编辑模式" close={()=>setShowLogin(false)}><form onSubmit={login}><label>编辑密码<input name="password" type="password" autoFocus required/></label><button className="primary">登录并初始化 CMS</button></form></Dialog>}
    {editing&&<Dialog title={editing.id?"编辑内容":"新建内容"} close={()=>setEditing(null)}><form onSubmit={save}><label>标题<input name="title" defaultValue={editing.title} required maxLength={100}/></label><div className="row"><label>类型<select name="type" defaultValue={editing.type}><option>笔记</option><option>项目</option></select></label><label>分类<input name="category" defaultValue={editing.category}/></label><label>排序<input name="sort" type="number" defaultValue={editing.sort}/></label></div><label>摘要<textarea name="summary" defaultValue={editing.summary} rows={2}/></label><label>正文<textarea name="content" defaultValue={editing.content} rows={10}/></label><label className="check"><input name="published" type="checkbox" defaultChecked={editing.published}/>公开发布</label><button className="primary">保存到 Notion</button></form></Dialog>}
  </main>;
}
function Section({id,title,items,editor,edit}:{id:string;title:string;items:Item[];editor:boolean;edit:(i:Item)=>void}){return <section className="collection" id={id}><div className="sectionTitle"><h2>{title}</h2><span>{items.length.toString().padStart(2,"0")}</span></div><div className="grid">{items.length?items.map(item=><article key={item.id}><div className="meta"><span>{item.category}</span>{!item.published&&<b>草稿</b>}</div><h3>{item.title}</h3><p>{item.summary||item.content.slice(0,120)}</p><div className="content">{item.content}</div>{editor&&<button onClick={()=>edit(item)}>编辑</button>}</article>):<p className="empty">还没有{title}。</p>}</div></section>}
function Dialog({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="dialog" role="dialog" aria-modal="true"><div className="dialogHead"><h2>{title}</h2><button onClick={close} aria-label="关闭">×</button></div>{children}</div></div>}
